$(function(){moment.tz.add({zones:{"Europe/Minsk":"1:50:16 - LMT 1880 1:50:16;1:50 - MMT 1924_4_2 1:50;2 - EET 1930_5_21 2;3 - MSK 1941_5_28 3;1 C-Eur CE%sT 1944_6_3 2;3 Russia MSK/MSD 1990 3;3 - MSK 1991_2_31_2 3;3 - EEST 1991_8_29_2 2;2 - EET 1992_2_29_0 2;3 - EEST 1992_8_27_0 2;2 Russia EE%sT 2011_2_27_2 2;3 - FET".split(";")},rules:{"C-Eur":"1916 1916 3 30 7 23 0 1 S;1916 1916 9 1 7 1 0 0;1917 1918 3 15 1 2 2 1 S;1917 1918 8 15 1 2 2 0;1940 1940 3 1 7 2 2 1 S;1942 1942 10 2 7 2 2 0;1943 1943 2 29 7 2 2 1 S;1943 1943 9 4 7 2 2 0;1944 1945 3 1 1 2 2 1 S;1944 1944 9 2 7 2 2 0;1945 1945 8 16 7 2 2 0;1977 1980 3 1 0 2 2 1 S;1977 1977 8 0 8 2 2 0;1978 1978 9 1 7 2 2 0;1979 1995 8 0 8 2 2 0;1981 9999 2 0 8 2 2 1 S;1996 9999 9 0 8 2 2 0".split(";"),
Russia:"1917 1917 6 1 7 23 0 1 MST;1917 1917 11 28 7 0 0 0 MMT;1918 1918 4 31 7 22 0 2 MDST;1918 1918 8 16 7 1 0 1 MST;1919 1919 4 31 7 23 0 2 MDST;1919 1919 6 1 7 2 0 1 S;1919 1919 7 16 7 0 0 0;1921 1921 1 14 7 23 0 1 S;1921 1921 2 20 7 23 0 2 M;1921 1921 8 1 7 0 0 1 S;1921 1921 9 1 7 0 0 0;1981 1984 3 1 7 0 0 1 S;1981 1983 9 1 7 0 0 0;1984 1991 8 0 8 2 2 0;1985 1991 2 0 8 2 2 1 S;1992 1992 2 6 8 23 0 1 S;1992 1992 8 6 8 23 0 0;1993 2010 2 0 8 2 2 1 S;1993 1995 8 0 8 2 2 0;1996 2010 9 0 8 2 2 0".split(";")},
links:{}})});

(function(c,m){var l=0;c.widget("ui.tabs",{version:"1.10.3.1-micro",delay:300,options:{active:null,event:"click",heightStyle:"content",hide:null,show:null,activate:null,beforeActivate:null,beforeLoad:null,load:null},_create:function(){var a=this.options;this.running=!1;this.element.addClass("ui-tabs ui-widget ui-widget-content ui-corner-all");this._processTabs();a.active=this._initialActive();this.active=!1!==this.options.active&&this.anchors.length?this._findActive(a.active):c();this._refresh()},
_initialActive:function(){var a=this.options.active;null===a&&(null===a&&(a=this.tabs.index(this.tabs.filter(".ui-tabs-active"))),null===a||-1===a)&&(a=this.tabs.length?0:!1);!1!==a&&(a=this.tabs.index(this.tabs.eq(a)),-1===a&&(a=0));!1===a&&this.anchors.length&&(a=0);return a},_getCreateEventData:function(){return{tab:this.active,panel:this.active.length?this._getPanelForTab(this.active):c()}},_setOption:function(a,b){"active"===a?this._activate(b):(this._super(a,b),"event"===a&&this._setupEvents(b),
"heightStyle"===a&&this._setupHeightStyle(b))},_tabId:function(a){return a.attr("aria-controls")||"ui-tabs-"+ ++l},_sanitizeSelector:function(a){return a?a.replace(/[!"$%&'()*+,.\/:;<=>?@\[\]\^`{|}~]/g,"\\$&"):""},_refresh:function(){this._setupEvents(this.options.event);this._setupHeightStyle(this.options.heightStyle);this.tabs.not(this.active).attr({"aria-selected":"false",tabIndex:-1});this.panels.not(this._getPanelForTab(this.active)).hide().attr({"aria-expanded":"false","aria-hidden":"true"});
this.active.length?(this.active.addClass("ui-tabs-active ui-state-active").attr({"aria-selected":"true",tabIndex:0}),this._getPanelForTab(this.active).show().attr({"aria-expanded":"true","aria-hidden":"false"})):this.tabs.eq(0).attr("tabIndex",0)},_processTabs:function(){var a=this;this.tablist=this._getList().addClass("ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all").attr("role","tablist");this.tabs=this.tablist.find("> li:has(a[href])").addClass("ui-state-default ui-corner-top").attr({role:"tab",
tabIndex:-1});this.anchors=this.tabs.map(function(){return c("a",this)[0]}).addClass("ui-tabs-anchor").attr({role:"presentation",tabIndex:-1});this.panels=c();this.anchors.each(function(b,e){var f,d,g=c(e).uniqueId().attr("id"),h=c(e).closest("li"),k=h.attr("aria-controls");f=e.hash;d=a.element.find(a._sanitizeSelector(f));d.length&&(a.panels=a.panels.add(d));k&&h.data("ui-tabs-aria-controls",k);h.attr({"aria-controls":f.substring(1),"aria-labelledby":g});d.attr("aria-labelledby",g)});this.panels.addClass("ui-tabs-panel ui-widget-content ui-corner-bottom").attr("role",
"tabpanel")},_getList:function(){return this.element.find("ol,ul").eq(0)},_createPanel:function(a){return c("<div>").attr("id",a).addClass("ui-tabs-panel ui-widget-content ui-corner-bottom").data("ui-tabs-destroy",!0)},_setupEvents:function(a){var b={click:function(a){a.preventDefault()}};a&&c.each(a.split(" "),function(a,c){b[c]="_eventHandler"});this._off(this.anchors.add(this.tabs).add(this.panels));this._on(this.anchors,b);this._focusable(this.tabs);this._hoverable(this.tabs)},_setupHeightStyle:function(a){var b,
e=this.element.parent();"fill"===a?(b=e.height(),b-=this.element.outerHeight()-this.element.height(),this.element.siblings(":visible").each(function(){var a=c(this),d=a.css("position");"absolute"!==d&&"fixed"!==d&&(b-=a.outerHeight(!0))}),this.element.children().not(this.panels).each(function(){b-=c(this).outerHeight(!0)}),this.panels.each(function(){c(this).height(Math.max(0,b-c(this).innerHeight()+c(this).height()))}).css("overflow","auto")):"auto"===a&&(b=0,this.panels.each(function(){b=Math.max(b,
c(this).height("").height())}).height(b))},_eventHandler:function(a){var b=this.options,e=this.active,f=c(a.currentTarget).closest("li"),d=f[0]===e[0],g=this._getPanelForTab(f),h=e.length?this._getPanelForTab(e):c(),e={oldTab:e,oldPanel:h,newTab:f,newPanel:g};a.preventDefault();f.hasClass("ui-state-disabled")||f.hasClass("ui-tabs-loading")||this.running||d||(b.active=this.tabs.index(f),this.active=d?c():f,h.length||g.length||c.error("jQuery UI Tabs: Mismatching fragment identifier."),this._toggle(a,
e))},_toggle:function(a,b){function e(){d.running=!1;d._trigger("activate",a,b)}function f(){b.newTab.closest("li").addClass("ui-tabs-active ui-state-active");g.length&&d.options.show?d._show(g,d.options.show,e):(g.show(),e())}var d=this,g=b.newPanel,h=b.oldPanel;this.running=!0;h.length&&this.options.hide?this._hide(h,this.options.hide,function(){b.oldTab.closest("li").removeClass("ui-tabs-active ui-state-active");f()}):(b.oldTab.closest("li").removeClass("ui-tabs-active ui-state-active"),h.hide(),
f());h.attr({"aria-expanded":"false","aria-hidden":"true"});b.oldTab.attr("aria-selected","false");g.length&&h.length?b.oldTab.attr("tabIndex",-1):g.length&&this.tabs.filter(function(){return 0===c(this).attr("tabIndex")}).attr("tabIndex",-1);g.attr({"aria-expanded":"true","aria-hidden":"false"});b.newTab.attr({"aria-selected":"true",tabIndex:0})},_activate:function(a){a=this._findActive(a);a[0]!==this.active[0]&&(a.length||(a=this.active),a=a.find(".ui-tabs-anchor")[0],this._eventHandler({target:a,
currentTarget:a,preventDefault:c.noop}))},_findActive:function(a){return!1===a?c():this.tabs.eq(a)},_getIndex:function(a){"string"===typeof a&&(a=this.anchors.index(this.anchors.filter("[href$='"+a+"']")));return a},_destroy:function(){this.element.removeClass("ui-tabs ui-widget ui-widget-content ui-corner-all");this.tablist.removeClass("ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all").removeAttr("role");this.anchors.removeClass("ui-tabs-anchor").removeAttr("role").removeAttr("tabIndex").removeUniqueId();
this.tabs.add(this.panels).each(function(){c.data(this,"ui-tabs-destroy")?c(this).remove():c(this).removeClass("ui-state-default ui-state-activeui-corner-top ui-corner-bottom ui-widget-content ui-tabs-active ui-tabs-panel").removeAttr("tabIndex").removeAttr("aria-live").removeAttr("aria-busy").removeAttr("aria-selected").removeAttr("aria-labelledby").removeAttr("aria-hidden").removeAttr("aria-expanded").removeAttr("role")});this.tabs.each(function(){var a=c(this),b=a.data("ui-tabs-aria-controls");
b?a.attr("aria-controls",b).removeData("ui-tabs-aria-controls"):a.removeAttr("aria-controls")});this.panels.show();"content"!==this.options.heightStyle&&this.panels.css("height","")},load:function(a,b){a=this._getIndex(a);this._activate(a)},_getPanelForTab:function(a){a=c(a).attr("aria-controls");return this.element.find(this._sanitizeSelector("#"+a))}})})(jQuery);

var Util=function(){var f=function(a,b){return moment(a).format(b?b:"MMM\u2013YYYY")};return{parseProfileDate:function(a){return moment(a,"MMM, YYYY").toDate()},formatMonthDuration:function(a){if(0==a)return"one month";var b=~~(a/12);a%=12;return(1<b?b+" years":1==b?"1 year":"")+(0<a?(0<b?" and ":"")+(1==a?"1 month":a+" months"):"")},formatRangeVerbose:function(a,b,c,d){c=moment(c);d=moment(d);var e=c.year()==d.year()&&c.month()==d.month();return(e?"":a+" ")+f(c,"MMMM, YYYY")+(e?"":" "+b+" "+f(d,
"MMMM, YYYY"))},formatRange:function(a,b){return f(a,"MMM\u2013YYYY")+" \u2013 "+f(b,"MMM\u2013YYYY")},formatPercents:function(a){return Math.round(100*a)+"%"},chooseRateLabel:function(a,b){for(var c=0;c<b.length&&!(a<=b[c][0]);c++);return b[c][1]},getMonthEnd:function(a){return moment(a).add("M",1).subtract("d",1).toDate()},getMonthDuration:function(a,b){a=moment(a);b=moment(b);var c=b.month()-a.month(),d=b.year()-a.year(),e=b.date()-a.date();return 12*d+c+(15<e?1:0)},viewed:function(a,b){var c=
$(a).offset().top,d=c+$(a).height(),e=$(b).filter(function(){var a=$(this).offset().top;$(this).height();return a>=c&&a<=d});return e=e.sort(function(a,b){return $(a).offset().top-$(b).offset().top})},buildColorGradient:function(a,b,c){var d=[],e=a.substr(1).match(/.{1,2}/g),f=b.substr(1).match(/.{1,2}/g);$.each(e,function(a,b){e[a]=parseInt(b,16)});$.each(f,function(a,b){f[a]=parseInt(b,16)});for(a=0;a<c;a++){d.push("#");b=a/(c-1);for(var g=0;3>g;g++){var h=e[g]+~~(b*(f[g]-e[g]));d[d.length-1]+=
(16>h?"0":"")+h.toString(16)}}return d},clamp:function(a,b,c){return b<a?a:b>c?c:b}}}();

var HeaderFx=function(){var g=Util.buildColorGradient("#666666","#eeeeff",41),d=g.length-1,a=null,k=0,l=0,h=_.throttle(function(){var b=e.position().left,a=e.position().top,c=e.width(),f=e.height(),b=[b+c/2,a+f/2],b=[b[0]-k,b[1]-l],a=[2/c,2/f],c=1/Math.sqrt(c*c/4+f*f/4),f=[50,2],c=~~(a[0]*b[0]*f[0])+"px "+~~(a[1]*b[1]*f[1])+"px "+~~(c*Math.sqrt(b[0]*b[0]+b[1]*b[1])*10+1)+"px "+g[d];e.css("text-shadow",c)},25),e=$(".header .title div");$("body").mousemove(function(a){k=a.clientX;l=a.clientY;h()});
e.mouseenter(function(){a&&clearInterval(a);a=setInterval(function(){0<d&&d--;0==d&&(clearInterval(a),a=null);h()},5)});e.mouseleave(function(){a&&clearInterval(a);a=setInterval(function(){d<g.length-1&&d++;d==g.length-1&&(clearInterval(a),a=null);h()},25)});return{}};

function Data(k){var b;(function(){b=k;var f=0,a=0,g=_.keys(b.companies).length;$.each(b.companies,function(b,d){var c=0;$.each(d.projects,function(b,a){a.company=d;var e=a.range;1==e.length&&e.push(e[0]);e={startDate:Util.parseProfileDate(a.range[0]),endDate:Util.getMonthEnd(Util.parseProfileDate(a.range[1]))};e.duration=Util.getMonthDuration(e.startDate,e.endDate);c+=e.duration;a.stats=e;a.isFirst=0==b;a.isLast=b==d.projects.length-1;a.index=b});d.stats={duration:c,startDate:d.projects[0].stats.startDate,
endDate:d.projects[d.projects.length-1].stats.endDate};d.name=b;d.isFirst=0==a;d.isLast=a==g-1;d.index=a;f+=c;a++});var c=0,h=0;$.each(b.companies,function(b,a){$.each(a.projects,function(b,a){a.stats.rate=a.stats.duration/f;c=Math.min(c,a.stats.rate);h=Math.max(h,a.stats.rate)})});var l=Util.buildColorGradient("#c0c0c0","#333333",101);$.each(b.companies,function(a,b){$.each(b.projects,function(b,a){a.stats.rateNorm=(a.stats.rate-c)/(h-c);a.stats.rateLabel=Util.chooseRateLabel(a.stats.rateNorm,[[0.1,
"Minor"],[0.25,"Short"],[0.5,"Medium"],[0.75,"Long"],[1,"Very long"]]);a.stats.rateColor=l[~~(100*a.stats.rateNorm)]})})})();return{findCompanyByIndex:function(f){if(!b)return null;for(var a in b.companies)if(b.companies[a].index==f)return b.companies[a];return null},findProjectByIndex:function(f,a){if(!b)return null;for(var g in b.companies)if(b.companies[g].index==f)for(var c in b.companies[g].projects)if(a==b.companies[g].projects[c].index)return b.companies[g].projects[c];return null},getCompanies:function(){return b.companies}}}

function ExperienceChart(l){var f,e,d={title:{text:""},legend:{enabled:!1},chart:{inverted:!0,animation:!1,reflow:!1,backgroundColor:"#f0f0f0",ignoreHiddenSeries:!1,renderTo:$("#timeline")[0],width:50,height:100,marginLeft:15,marginRight:15},plotOptions:{line:{animation:!1,lineWidth:5,marker:{enabled:!1}}},xAxis:{type:"datetime",reversed:!1,tickWidth:0,gridLineWidth:0,gridLineColor:"#FEFEFE",lineWidth:0,lineColor:"#CC0000",minorGridLineWidth:0,minorGridLineColor:"#CC0000",minRange:1E3,labels:{x:-1,
step:1,rotation:270,formatter:function(){return moment(this.value).format("YYYY")}}},yAxis:{min:-0.001,max:0.001,minTickInterval:5,labels:{enabled:!1},title:{enabled:!1},tickWidth:0,gridLineWidth:0,gridLineColor:"#FEFEFE",lineWidth:0,lineColor:"#CC0000",minorGridLineWidth:0,minorGridLineColor:"#CC0000"},tooltip:{enabled:!1}};(function(){f=l;if(!$(".highcharts-container").length){d.series=[];$.each(f.getCompanies(),function(a,b){var c={data:[],type:"line",animation:!1};$.each(b.projects,function(a,
b){var d={project:b,y:0};c.data.push(d);c.data[c.data.length-1].x=b.stats.startDate;b.isLast&&(c.data.push(_.clone(d)),c.data[c.data.length-1].x=b.stats.endDate,c.data[c.data.length-1].isSerieEnd=!0)});d.series.push(c)});d.xAxis.plotLines=[];for(var g=moment("2005-01-01");g.isBefore(moment().add("M",1));g.add("y",1))d.xAxis.plotLines.push({value:moment(g),dashStyle:"Solid",color:"#999",width:1});d.colors=["#55AADD","#55DDAA"];e=new Highcharts.Chart(d);$("path").attr("stroke-linecap","butt");$("svg > text").remove();
$(".highcharts-container").css("overflow","visible");$(".highcharts-markers").remove();var m=_.template($("#project-tpl").html());$.each(f.getCompanies(),function(a,b){$.each(b.projects,function(a,b){$("#experience .details").prepend($(m({project:b})))})});var k=function(){var a=$("#experience .details").height();e.setSize(d.chart.width,a,!1);var b=$("#experience .details .project > table").height();$.each($("#experience .details .project > table"),function(a,c){b=Math.min(b,$(c).height())});var c=
$("#experience .details .project.first[company-index=0]");c.css("margin-bottom",a-c.height()-b+20)},h=function(a){a=Util.viewed($("#experience .details"),$("#experience div.project > table"))[0];a=$(a).parent();$("#experience .details .infocus").removeClass("infocus");$(a).toggleClass("infocus",!0);a=f.findProjectByIndex($(a).attr("company-index"),$(a).attr("project-index"));e.xAxis[0].removePlotBand("highlight-selection");e.xAxis[0].removePlotBand("highlight-project");e.xAxis[0].addPlotBand({from:a.stats.startDate,
to:a.stats.endDate,color:d.colors[a.company.index%2],id:"highlight-selection"})};$(".details").scroll(h);$(window).on("resize",function(){k();h()});k();h();$("#experience .project .date .range").mousemove(function(){var a=$(this).closest("#experience .project").attr("company-index"),b=$(this).closest("#experience .project").attr("project-index"),a=f.findProjectByIndex(parseInt(a),parseInt(b));e.xAxis[0].addPlotBand({from:a.stats.startDate,to:a.stats.endDate,color:["#77CCFF","#77FFDD"][a.company.index%
2],id:"highlight-project"})}).mouseleave(function(){e.xAxis[0].removePlotBand("highlight-project")});$("#experience div.details").niceScroll({mousescrollstep:20,sensitiverail:!1,background:"#d6d6d6",spacebarenabled:!1,cursorwidth:12,hidecursordelay:268435455,horizrailenabled:!1})}})();return{}};

function SkillCloud(m){var l=function(c){if(!c)return null;var a=[];$.each(c,function(c,k){a.push({name:c,count:k.count,sub:l(k.sub)})});return a=a.sort(function(a,c){return c.count-a.count})};(function(){if(!(0<$("div.technologies .tag").length)){var c={};$.each(m.getCompanies(),function(a,g){$.each(g.projects,function(a,f){var b=f.skills.split(",");$.each(b,function(a,b){var e=$.trim(b);c[e]||(c[e]=[]);c[e].push(f)})})});var a={};$.each(c,function(c,g){var d=0;$.each(g,function(a,b){d+=b.stats.duration});
var f=c.split("("),b=$.trim(f[0]);a[b]||(a[b]={count:0});a[b].count+=d;if(1<f.length){a[b].sub||(a[b].sub={});var h=f[1].replace(/\)/g,"").split(";");$.each(h,function(a,b){h[a]=$.trim(b)});$.each(h,function(c,e){a[b].sub[e]||(a[b].sub[e]={count:0});a[b].sub[e].count+=d})}});var n=_.template($("#skill-tpl").html());$.each(l(a),function(a,c){var d=n({skill:c}),d=d.replace(/\n/g,"").replace(/(>)(\s*)(\S*)/g,"$1$3").replace(/(\S*)(\s*)(<)/g,"$1$3").replace(/(\S*)(\s*)(\()/g,"$1$3").replace(/(\))(\s*)(\S*)/g,
"$1$3").replace(/(>)(\s*)(\))/g,"$1$3");$(".skills .technologies").append(d)});$(".skills .technologies .tag").tooltip({show:{effect:"fade",duration:10}});$(".skills .technologies div.tag.skill").mousemove(function(){$(this).attr("aria-describedby")||($(this).attr("title")||$(this).attr("title",$(this).attr("alttitle")),$(this).tooltip("open"))})}})();return{}}

var Profile={companies:{"EPAM, Travel Solutions Department":{projects:[{range:["Apr, 2005","Jun, 2005"],name:"South African Airways booking",desc:"Web application for flight itinerary search and reservation.",role:"Java developer",participation:"Presentation layer and business logic implementation.",achievements:"Promoted JSP Tag unit tests.",skills:"Java, JSP/EL/JSTL, HTML/CSS, Struts 1.x, JUnit, WSDL, Apache Axis, Java EE (Servlets)",team:"5-10",tools:"Tomcat, VSS"},{range:["Jul, 2005","Dec, 2005"],
name:"Scandinavian Airlines booking",desc:"Web application for flight itinerary search and reservation. Have original design.",role:"Web developer, Java developer",participation:"Presentation layer and business logic implementation.",achievements:"Perfect teamwork, happy customer.",skills:"Javascript, DWR, Java, JSP/EL/JSTL, HTML/CSS, Struts 1.x, JUnit, WSDL, Apache Axis, Java EE (Servlets)",team:"5-10",tools:"Tomcat, VSS"},{range:["Jan, 2006","Sep, 2006"],name:"Vail Resorts call center",desc:"Web frontend with BREAD-functionality for reservation management service.",
role:"Web developer, Java developer",participation:"Research and architecture on web communication layer. Development and support of custom BREAD MVC framework.",achievements:"Introduction of custom model-view javascript framework.",skills:"Javascript, Java, JSP/EL/JSTL, HTML/CSS, Struts 1.x, JUnit, WSDL, Apache Axis, Java EE (Servlets)",team:"5-10",tools:"Tomcat, Ant, VSS"},{range:["Oct, 2006","Aug, 2007"],name:"Travel Distribution Platform",desc:"Platform for online booking web applications.",role:"Java developer",
participation:"Design and development of booking services. Assisting with integration.",achievements:"Good experience with web services.",skills:"UML, Java, Struts 1.x, JSP/EL/JSTL, JUnit, WSDL, Apache Axis)",team:"10-15",tools:"Enterprise Architect, CVS/SVN"}]},"EPAM, Hyperion Department":{projects:[{range:["Sep, 2007","Jan, 2008"],name:"Hyperion Strategic Finance / Profitability module",desc:"Web client software for development of financial plan.",role:"Java developer, Web developer",participation:"Module component development: UI, business logic, testing and integration.",
achievements:"Got some Java EE experience.",skills:"Java, Java EE (Servlets; JMS; EJB; JSF), ORM (TopLink), SQL, Bindows",team:"15-20",tools:"MS SQL Server, Essbase, Oracle DB, Hyperion Workspace, ClearCase"}]},"Generation-P consulting ltd.":{projects:[{range:["Feb, 2008","Jun, 2008"],name:"Web application for job surveys service",desc:"Online survey for a big job agency. Featuring automatic survey management, analysis and report tools.",role:"Consultant, Java developer",participation:"Architecture optimization: transaction safety, deadlocks, memory usage, performance, clustering. Performance and functional testing tools. Code review. EJB 2.0 upgrade to EJB 3.0. Spring integration.",
achievements:"Successfully improved performance and stability of application.",skills:"Java, Java EE (Servlets; JMS; EJB), ORM (Hibernate), SQL, Clustering (JOnAS), Spring (DI), JUnit",team:"4",tools:"MyEclipse, Ant, Maven, Oracle DB, JOnAS, SQLDeveloper, Meld, CVS"}]},Agava:{projects:[{range:["Aug, 2008"],name:"Adbroker.ru instant search",desc:"Web advertisements management system: ads trade, management, control, statistics.",role:"Web developer, Java developer",participation:"Development of instant search.",
achievements:"Introduced minor performance optimization on instant search.",skills:"Java, Java EE (Servlets; EJB; Web services), ORM (Hibernate), SQL, JBoss Seam, Axis, Javascript(jQuery), HTML/CSS, XSLT",team:"1",tools:"JBoss, CVS"},{range:["Sep, 2008","Nov, 2008"],name:"Rebot.ru web development",desc:"News feed reader, which knows what news will be interesting to the user.",role:"Web developer",participation:"WSDL development, web frontend development, integration with Agava CRM.",achievements:"Boost on HTML/CSS skills.",
skills:"Java, Javascript(jQuery), HTML/CSS, Java EE (Servlets; Web services), Axis, Axis WSF",team:"2-3",tools:"JBoss, Apache HTTP, nginx, ant, CVS"}]},"Specific Group AG":{projects:[{range:["Mar, 2009","Apr, 2010"],name:"European Gate",desc:"Server application for format conversion of financial transaction. With web client for control/monitoring.",role:"Technical writer, Java developer, Web developer",participation:"Project documentation, status feedback, code review, architecture review. Consulting branch department. Introduction of CI process. Web client improvements, wicket model optimization. Conversion compatibility testing framework development.",
achievements:"Documentation process introduction. Multiple code and process optimizations.",skills:"ANTLR, UML, Java, Spring (DI; ORM), Wicket, HTML/CSS, ORM (Hibernate), Java EE(Servlets)",team:"5-7",tools:"Tomcat, Enterprise Architect, Confluence, Cruise Control, Nexus, Team City, SVN"}]},"Logic Way":{projects:[{range:["May, 2010"],name:"MSC Internal Affairs Archive",desc:"DB archive application to secure and manage official documentation.",role:"DB developer, Java developer",participation:"DB structure implementation and support. Development of database export/import utility.",
achievements:"Good DB experience.",skills:"Java, SQL, PL/SQL",team:"2",tools:"Oracle, IBM DB2, Toad, CVS"},{range:["Jun, 2010","Nov, 2010"],name:"MSC Council Archive",desc:"Web application to store, secure, manage, browse and share official documentation.",role:"SQL developer, Java developer, Web developer, Team lead",participation:"Development of UI BREAD engine and UI implementation. Frontend application DB/BL/Services development. Development of IBM ICM interface utility (ICM operations interface, data export/import/synchronization).",
achievements:"Made AOP-based data caching for better performance.",skills:"Java, XML/XSD, Freemarker, HTML/CSS, Javascript, SQL, IBM CM, Javassist, Java EE(Servlets)",team:"1-3",tools:"Solaris, IBM DB2, IBM CM, IBM NSE, Tivoli storage, WebSphere AS, Tomcat, CVS"},{range:["Dec, 2010","May, 2011"],name:"Severstal ESK Contractor Management System",desc:"Web client application for contractors browsing and management (variety of specific business domain actions).",role:"Java developer, Team lead",participation:"Portal server maintenance, portlet implementation assistance, team training.",
achievements:"Helped customer to fix server failure after midnight.",skills:"Java, XML/XSD, WSDL, Axis, IBM XML Beans, JSP/EL/JSTL, HTML/CSS, Javascript(jQuery), Portlets, Java EE(Servlets)",team:"5-6",tools:"Oracle AS, Oracle Portal, Orion Portlet Provider, CVS"},{range:["Jun, 2011","Jul, 2011"],name:"PeopleNet logistics tracking",desc:"Web application which provide different services for logistics &mdash; tracking, optimization.",role:"Contractor, Java developer",participation:"Web service development.",
achievements:"Contractor experience, GWT experience.",skills:"Java, SQL, OSCi, ORM (Hibernate), Spring (DI; ORM), GWT, Ext GWT, Portlets, Java EE(Servlets, EJB)",team:"20-30",tools:"Karaf, Liferay, Tomcat, SVN"},{range:["Aug, 2011"],name:"Automated fine payment system",desc:"Module for fine payment in customs control application.",role:"SQL developer",participation:"Development of PL/SQL services.",achievements:"",skills:"PL/SQL",team:"1",tools:"Toad"},{range:["Sep, 2011","Jan, 2012"],name:"Whiteboard module for Mind.com webinars",
desc:"Whiteboard module for sharing drawings, images and documents at web video conference system.",role:"Lead developer, Team management",participation:"Technology assistance, project management, development.",achievements:"Project management skills, SVG experience.",skills:"Java, HTML/CSS, SVG, VML, RaphaelGWT, Raphael, Guava, ORM (Hibernate), Apache Batic, Javascript(jQuery), Java EE(Servlets)",team:"3",tools:"JBoss, PostGRE, Wowza, SVN"},{range:["Feb, 2012","Apr, 2012"],name:"Mind.com webinars",
desc:"Online webinars system.",role:"Java developer, Web developer",participation:"Development of various features and improvements.",achievements:"",skills:"Java, HTML/CSS, SVG, VML, RaphaelGWT, Raphael, Guava, Hibernate, Apache Batic, Java EE(Servlets)",team:"8",tools:"JBoss, PostGRE, Wowza, SVN"},{range:["May, 2012"],name:"YouTube downloader",desc:"Software which allows downloading youtube videos.",role:"Java developer",participation:"Research, development.",achievements:"",skills:"Java, YouTube API, FLV, Video encoding",
team:"1",tools:""},{range:["Jun, 2012"],name:"CeConvergence",desc:"Web application for tracking and notification of accountant training courses.",role:"Java developer",participation:"Development of various features.",achievements:"",skills:"Java, Spring (MVC; DI), PL/SQL",team:"5",tools:"Tomcat, Oracle, SVN"},{range:["Jul, 2012"],name:"Car insurance agency web services",desc:"Set of web services under Russian Car Insurance Association to be used by local agencies.",role:"Java developer",participation:"Development of MQ manager and web services.",
achievements:"",skills:"Java, Spring (DI), PL/SQL",team:"10-15",tools:"Tomcat, Oracle, CVS"},{range:["Aug, 2012","Nov, 2012"],name:"Customs Management application",desc:"Web client to manage customs database entities, made on base of existing Delphi application.",role:"Lead developer",participation:"Architecture development and support, base components development, team coordination.",achievements:"Automatic DFM form to HTML layout conversion.",skills:"Java, Wicket, HTML/CSS, Spring (DI; ORM), SQL, ORM (Hibernate), Javascript(jQuery), Java EE(Servlets)",
team:"3-10",tools:"Tomcat, CVS"}]},Fitbit:{projects:[{range:["Dec, 2012","Dec, 2013"],name:"Fitbit Corporate Wellness",desc:"Web application for monitoring corporate personnel physical activity.",role:"Web developer, Java developer",participation:"Development, support, improvement of charts functionality. Development and support of various web widgets. Development of OAuth authentication flow.",achievements:"Major boost on web skills. Getting over highcharts limits. Advanced Agile methodology experience.",
skills:"Javascript (jQuery; Backbone; Underscore; Highcharts), HTML/CSS, SVG, VML, Raphael, JSP/EL/JSTL, Java, Spring (DI; MVC; REST), Stripes, Guava, Java EE(Servlets, JMS), ORM (Hibernate), NoSQL (Cassandra)",team:"10-15",tools:"Tomcat, Oracle, Cassandra, SVN, Git, Fiddler"}]}}};

var Main=function(){var d,c=new function(){var b=new function(){return{set:{summary:new function(){var a;return{init:function(){a||(a=new HeaderFx)}}},experience:new function(){var a;return{init:function(){a||(a=new ExperienceChart(d))}}},skills:new function(){var a;return{init:function(){a||(a=new SkillCloud(d))}}},contact:new function(){var a,b=function(){var b=function(){var a=moment().tz("Europe/Minsk");$(".time").html(a.format("hh:mm:ss A"))};b();a=setInterval(b,1E3)};return{init:function(){a||
b()}}}},indexById:function(a){return["summary","experience","skills","contact"].indexOf(a)}}},c=function(){$(".summary .navigation-hint a").mousedown(function(){e($(this).attr("href").substr(1))}).click(function(a){a.preventDefault()});$(".navigation-hint a").mouseenter(function(){$("li[aria-controls="+$(this).attr("href").substr(1)+"]").css({backgroundColor:"#FFF"},300).stop().animate({backgroundColor:"#EEF"},300)}).mouseleave(function(){$("li[aria-controls="+$(this).attr("href").substr(1)+"]").stop().animate({backgroundColor:"#FEFEFE"},
300)})},e=function(a){$("div.wrapper").tabs("load",b.indexById(a))},f=function(){$("div.wrapper").tabs({activate:function(a,d){e(d.newPanel.attr("id"));var c=d.newPanel.attr("id");$("body").toggleClass("fluid","experience"==c);$(".nicescroll-rails").toggle("experience"==c);b.set[c].init()},event:"mousedown"});b.set.summary.init();$(".nav").css("visibility","visible");$(".nav li").click(function(a){a.preventDefault()});$(".nav li").mouseenter(function(){$(this).hasClass("ui-tabs-active")||$(this).css({backgroundColor:"#FEFEFE"},
300).stop().animate({backgroundColor:"#EEF"},300)}).mouseleave(function(){$(this).hasClass("ui-tabs-active")||$(this).stop().animate({backgroundColor:"#FEFEFE"},300)}).click(function(){$(".nav li").css({backgroundColor:"#FEFEFE"});$(".nav li.ui-tabs-active").css({backgroundColor:"#EEF"})})};return{init:function(){f();$(".nav li[role=tab]").unbind("keydown");c()}}};return{loadData:function(b){d=new Data(b);return this},start:function(){c.init();return this}}};$(function(){(new Main).loadData(Profile).start()}());